#!/bin/bash
# MacOS Requirements: brew install imagemagick ghostscript
# Alternative shot: magick "$f" -colorspace gray -auto-level -threshold 50% "clean_$f"

for f in *.jpg; do
  magick "$f" -colorspace gray -blur 0x1 -auto-level -morphology Open Diamond:1 -threshold 60% "$f".png && convert *.png output.pdf
done
